### ISSUE TITLE
Add `.gitignore` file 

### ISSUE THREAD

**Issue by dinhanhx** [mohamedbenchikh/MDML#1]
It seems like your repos has some `pyc` files (which are python cache - binary files). You should ignore them.

If you are lazy enough, just use [conventional .gitignore file](https://github.com/github/gitignore/blob/main/Python.gitignore) for Python.

**Comment by mohamedbenchikh** [comment]
**.gitignore** and **.gitattributes** have been added to the repo, Thanks!
