### ISSUE TITLE
AttributeError: 'XGBModel' object has no attribute 'feature_types'

### ISSUE THREAD

**Issue by electrum21** [mohamedbenchikh/MDML#3]
i got this error when i submitted a sample exe file... how can i get around this error?

**Comment by mohamedbenchikh** [comment]
Hi,
delete *.joblib files in models directory and try again

**Comment by electrum21** [comment]
hi, i just resolved the issue by installing xgboost==1.6.0
that may be the issue because i previously faced the error using the latest version of xgboost... you may want to update that in the requirements.txt.

thank you!
